### PR TITLE
included export_kernel_fpu_functions_[4_14 / 5_3].patch and appropria…

### PR DESCRIPTION
**Pull request by shadowrylander**
…te settings to boot an [encrypted] zfs root

### CODE REVIEW

**Comment by anthe** [comment]
Hey! You did it!

**Comment by shadowrylander** [comment]
I know, right? I can't believe it myself! 😹 Thank you so very, very much for all the help!

**Comment by shadowrylander** [comment]
Oh... Oh dear... I forgot the patches themselves!

**Comment by deliciouslytyped** [comment]
Yeah, would be nice if you could uhh, add those. Left me scratching my head for a bit there.

**Comment by shadowrylander** [comment]
@deliciouslytyped Already requested!

**Comment by anthe** [comment]
Oops, done now

**Comment by shadowrylander** [comment]
Sorry about that; I forgot to `git add`!

**Comment by deliciouslytyped** [comment]
I just remembered though, doesnt NixOS include such a patch by default? or does it end up disabled somehow with this kernel?

**Comment by shadowrylander** [comment]
You'd think that, wouldn't you? But apparently, yes, it does seem to get disabled somehow. So I dunno. 😹

**Comment by deliciouslytyped** [comment]
That might be worth looking into.

**Comment by shadowrylander** [comment]
Well, I'll be useless there; I'm still getting used to NixOS, and the syntax is still quite confusing to me!

**Pull request merged**
